apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: dev
spec:
  cassandra:
    serverVersion: {{ .values.cassandra.serverVersion }}
    datacenters:
      - metadata:
          name: {{ .values.cassandra.dc_name }}
        size: {{ .values.cassandra.replicas }}
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 512M
        stargate:
          size: 1
          heapSize: 256M
